# Generated by Django 6.0.1 on 2026-02-05 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.orderitem'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product', 'order_item')},
        ),
    ]
