# Generated by Django 6.0.1 on 2026-02-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_review_unique_together_review_order_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'street', 'city', 'phone', 'pin_code')},
        ),
    ]
